### PR TITLE
Fix progress bar updates and initialize bars at start of scan/loop

### PR DESCRIPTION
**Pull request by andrewlesak**
Supersedes and fixes problems outlined in #26. I think the issue was that the progress bar was updating too fast (or not in the correct order) after initialization in the control flow here, so the first update wouldn't process. 
```python
 def _update_progress_bar(iter_num, bar_id: int = 0):
    """Updates tqdm from a JAX scan or loop"""
    _ = jax.lax.cond(
        iter_num == 0,
        lambda _: callback(_define_tqdm, None, bar_id, ordered=True),
        lambda _: None,
        operand=None,
    )
    
    _ = jax.lax.cond(
        # update tqdm every multiple of `print_rate`
        (iter_num % print_rate == 0),
        lambda _: callback(_update_tqdm, print_rate, bar_id, ordered=True),
        lambda _: None,
        operand=None,
    )
```
It was really only a problem when using `print_rate = 1` which is likely why this wasn't caught until now. To fix this, we now initialize the progress bar as soon as the wrapper is called so that they exist before the loop/scan starts. Now we have to explicitly pass the progress bar index if we want to display multiple. Here's an example of how to do this that I added to the README:

```python
from jax_tqdm import PBar, scan_tqdm
from jax import lax
import jax.numpy as jnp

n = 10_000

def run_scan(bar_id):

    @scan_tqdm(n, bar_id=bar_id)
    def step(carry, x):
        return carry + 1, carry + 1

    # Wrap the initial value and pass the progress bar index
    init = PBar(id=bar_id, carry=0)
    last_number, all_numbers = lax.scan(step, init, jnp.arange(n))

    return last_number.carry, all_numbers

n_bars = 5
last_numbers, all_numbers = jax.vmap(run_scan)(jnp.arange(n_bars))
```

Also, we want to update completed iterations so we should be updating when `(iter_num + 1) % print_rate == 0`. With these changes, the progress bars are working beautifully. 

Here's the test code I was running:
```python
from jax_tqdm import PBar, scan_tqdm
import jax
import jax.numpy as jnp
import jax.random as jr

n = 10
print_rate = 3
arr_size = 9000

def run_loop(i):

    @scan_tqdm(n, print_rate, bar_id=i)
    def step(iter_num, val):
        rand_mat = jr.normal(jr.PRNGKey(iter_num), (arr_size, arr_size)) 
        mat_mul = rand_mat @ rand_mat.T
        return iter_num + 1, val + 1e-8 * jnp.sum(mat_mul)
    
    # Wrap the initial value and pass the progress bar index
    init = PBar(id=i, carry=0)
    final_value, all_vals = jax.lax.scan(step, init, jnp.arange(n))
    return final_value.carry, all_vals

num_bars = 5
bar_idxs = jnp.arange(num_bars)
last_iters, all_vals = jax.vmap(run_loop)(bar_idxs)
```

NOTE: don't test with `time.sleep()` since progress bar updates before the sleep has completed.

Here's what my updates look like now:

`n = 10` and `print_rate = 3`:
n_10_print_rate_3-ezgif com-optimize

`n = 10` and `print_rate = 1`:
n_10_print_rate_1-ezgif com-optimize

I updated the tests to work with the new code and passed them all running pytest on test_examples.py

Let me know what you guys think!

### CODE REVIEW

**Comment by zombie-einstein** [comment]
Looking into this this bug I think there's a few things going on here:

- There is a bug [here](https://github.com/jeremiecoullon/jax-tqdm/blob/f216dcb62561e58f5bac55a3983f40b412c9c14e/jax_tqdm/pbar.py#L190) when `iter_num` is 0 it should create a bar, but then in the next check `(iter_num % print_rate == 0)` is `True` and the bar is incorrectly update after being initialised (and before the actual scan step has completed). This can be fixed by checking `iter_num > 0`.
- It seems there is no guarantee that callback events are called as they appear in the code, i.e. inside the step we call `_update_progress_bar` then the inner function, then call `close_tqdm`. If there is some action performed in both of the progress bar functions, these can appear to occur too quickly. Conversely changes between calls to the scan step seem to be correctly spaced.
- There also seems to be a kind of bug where `remainder=0`, since the final update to complete the bar should be performed when the final iteration completes, this should be done when the bar is closed.
- There is an edge case when `print_rate=1` where the `n-1` update to the bar is run at the start of the iteration, but then the final bar update needs to be applied at the end of the iteration.

I've implemented these changes in [this branch](https://github.com/jeremiecoullon/jax-tqdm/tree/fix_iter_bug). Roughly the algorithm is

- Only init the bar when `iter_num=0` , then update at print rate for remaining iterations
- At the final iteration update the bar by the remaining amount (either the remainder, or `print_rate` if `remainder=0`) and close it.

I think this has the correct behaviour then, the only strange case is when `print_rate=1` the final update occurs quickly due to happening inside the same inner-step.

**Comment by zombie-einstein** [comment]
I'm a little unsure about the change you're proposing:

- I pictured the wrapping function as returning a the wrapped function, with the update functionality defined at compile-time. This seems to go against that, the wrapper is now dependent on the runtime values.
- This also binds the definition of the scanned/looped function to have to be inside the mapped function, that seems to decrease flexibility. The initial multi-bar design was intended to have minimal impact to the usage of wrapped functions.

**Comment by andrewlesak** [comment]
I understand your concerns and agree that it is unfortunate that the only fix I could come up with adds a bit of weight. But I would still argue that having the progress bar initialize immediately when the wrapper is called is valuable. 

For example, I am working with hidden Markov models (HMMs) in the Dynamax library. If I run a large model fit using the expectation-maximization (EM) algorithm, each update is potentially very costly and I want to display progress for each step. If I don't initialize the progress bars immediately, then I am forced to wait potentially minutes after executing my code until the progress bar finally shows up when the first iteration completes. I would argue that the psychological value of having the progress bar appear immediately at the start of a large model fit is worth the trouble. 

If I were to fit a model, I would have to call the following function
```python
fit_em(...):

    @scan_tqd(...)
    @jit
    em_step(...):
        # run E step
        # run M step
        return ...
 
    ... = lax.scan(em_step, init_carry, jnp.arange(num_iters))
```
so the scanned function `em_step()` is already inside the function `fit_em()`that I would map. This is a common scheme in many model fitting libraries so in these cases, it's no trouble at all to require the scanned function be inside the mapped function.

The changes I proposed in this PR are (maybe selfishly) useful for my applications, but I understand they may slightly go against the original philosophy of this package.

**Comment by andrewlesak** [comment]
I also took a look at the changes in your `fix_iter_bug` branch that you mentioned above. Using the test code in my first comment, this is what I observe: 

`n = 10` and `print_rate = 3`:
test_einstein_n10_rate3-ezgif com-optimize

`n = 10` and `print_rate = 1`:
test_einstein_n10_rate1-ezgif com-optimize

If I modify the code so that 
```python
        def _inner_update(i):
            return jax.lax.cond(
                (i+1) % print_rate == 0,  # show completed iters
                lambda: callback(_update_tqdm, bar_id, ordered=True),
                lambda: None,
            )
```
then this at least fixes the `print_rate != 1` case. But this still leaves the issue for `print_rate = 1`.

When I print which iter the loop is on in the body function, I can see that the progress bars still don't appear until after the first iter, which is mainly the problem that I set out to solve in this PR.

**Comment by zombie-einstein** [comment]
Looking into this more it's a strange one. Initially it's hard to see why this does not work correctly.

So faking work with a call back, for example the wrapping function is something like 

```python
@scan_tqdm
def step(carry, x):
    jax.debug.callback(lambda: time.sleep(10), ordered=True)
    return carry + 1,  x
```

Works correctly, the bar is created them the sleep waits then updates and so on, I guess because JAX knows . 

Replacing this with actual computation, it's almost like JAX pushes the callbacks to the back of the queue, so yeah the bar is shown first after the computation, and then if two callbacks are called, they happen instantaneously together (this is the source of the double update or skipping final steps). Tried a bunch of little tweaks but can't seem to change this ordering.

In the JAx docs they give an example around [callback ordering](https://jax.readthedocs.io/en/latest/debugging/print_breakpoint.html#asynchronous-callbacks)

```python
@jax.jit
def f(x):
    jax.debug.print("x: {}", x)
    return x

f(2.).block_until_ready()
jax.effects_barrier()
# Prints: x: 2.
# <do something else>
```

In a Python process this works to order the callbacks, but as far as I can tell inside a JIT compiled function it doesn't have any effect, which obviously in the case of scans and loops means the progress bar is not fixed.

Using [`io_callback`](https://jax.readthedocs.io/en/latest/_autosummary/jax.experimental.io_callback.html) from the experimental module does work (at least the bar is initialised before any work). The downside is you cannot use the callback inside a JAX conditional, and you cannot use `ordered=True`.  You can push the iteration checks into the callbacks, but not using the ordered flag seems to result in odd behaviour.

Appreciate how the uninitialised bar is a pain, going to look into this a bit more, seems like there should be some means of ensuring progress is updated before starting the computation inside the step function.

**Comment by andrewlesak** [comment]
Thanks for digging deeper into the source of this issue. I'll also experiment with trying to get the progress bars to initialize correctly without having to explicitly pass `bar_id`. It would be amazing if we could figure this out!

**Comment by andrewlesak** [comment]
I realized that my suggested changes of explicitly passing `bar_id` into the wrapper makes the `PBar` class obsolete. In case we go forward with my proposed changes, I adapted the code to remove this class (and chex dependency) and confirmed that the progress bars function properly as shown in my first comment. Also ran the lint and passed all tests.

**Comment by zombie-einstein** [comment]
Ok, think I got this! Was kind of obvious in the end.

So in the current implementation, there is no dependency between the callback and the inner function being called, i.e. `update_progress` since it has no return value and is independent of the rest of the steps

```python
bar_id = carry.id
carry = carry.carry
 _update_progress_bar(iter_num, bar_id=bar_id)
result = func(carry, x)
result = (PBar(id=bar_id, carry=result[0]), result[1])
return close_tqdm(result, iter_num, bar_id=bar_id)
```

So (I assume) when optimised and turned into a computation graph, there is no reason to run the call back prior to the computation.

The fix is to enforce this dependence by passing a value through the callback function (though it remains unchanged), in my case I'm passing the `carry` through the progress update. I've pushed these changes to my branch, and everything seems to work now if you want to try it out.

**Comment by zombie-einstein** [comment]
Created a PR #28 with suggested changes

**Comment by andrewlesak** [comment]
I will close this now thanks to the new PR solving the issues!

**Pull request closed without merging**
