### PR TITLE
Refactor host_callback as it is deprecated since v0.4.26

### PR DESCRIPTION
**Pull request by BirkhoffG**
## Background

* `jax.experimental.host_callback` was no longer supported on cloud tpu since [v0.4.8](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-8-march-29-2023) has been deprecated since [v0.4.26](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-26-april-3-2024). 

## What is this PR

* This PR refactors the reliance from `jax.experimental.host_callback` to `jax.debug.callback`

@jeremiecoullon @zombie-einstein

### CODE REVIEW

**Review by zombie-einstein — COMMENTED** [review]
Looks good to me. Do we need to update the minimum version of JAX?

**Comment by BirkhoffG** [comment]
I think the unit test passes after v0.4.12, so I would recommend updating the minimum version to v0.4.12.

**Comment by zombie-einstein** [comment]
> I think the unit test passes after v0.4.12, so I would recommend updating the minimum version to v0.4.12.

Sounds good, @jeremiecoullon happy to merge this, then I can make the version update and release?

**Comment by jeremiecoullon** [comment]
This looks good! Thanks for the PR @BirkhoffG 🙏

**Pull request merged**
